-- ============================================================
-- CUENTAS POR COBRAR — setup.sql v3
-- Ejecutar en el SQL Editor de Supabase para crear/actualizar
-- el esquema completo del módulo CxC.
-- ============================================================

-- ── 1. Limpiar tablas anteriores ─────────────────────────────
DROP TABLE IF EXISTS public.cxc_abonos  CASCADE;
DROP TABLE IF EXISTS public.cxc_manuales CASCADE;

-- ── 2. Tabla principal de Cuentas por Cobrar ─────────────────
--
--  Soporta AMBOS flujos:
--    origen = 'manual'          → creada desde el wizard manual
--    origen = 'local_comercial' → creada automáticamente desde una orden de local
--    origen = 'domicilio'       → creada automáticamente desde un pedido a domicilio
--
--  orden_origen_id: cuando el origen es automático, almacena el ID
--  de la orden de local_comercial u ordenes_domicilio para poder
--  eliminarla si el estado de esa orden cambia a "pagado".
-- ─────────────────────────────────────────────────────────────
CREATE TABLE public.cxc_manuales (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relación con cliente (FK suave — permite clientes nuevos aún no en BD)
    cliente_id          bigint REFERENCES public.clientes(id) ON DELETE SET NULL,
    cliente_nombre      text   NOT NULL,          -- desnormalizado para display rápido
    cliente_telefono    text,

    -- Vehículo
    vehiculo_placa      text,                     -- placa del vehículo asociado

    -- Detalle de la deuda
    concepto            text   NOT NULL,          -- descripción libre
    notas               text,                     -- observaciones opcionales
    fecha_deuda         date   NOT NULL DEFAULT CURRENT_DATE,

    -- Montos
    monto_total         numeric NOT NULL DEFAULT 0,
    saldo_pendiente     numeric NOT NULL DEFAULT 0,  -- se actualiza con cada abono

    -- Origen y estado
    origen              text   NOT NULL DEFAULT 'manual',  -- 'manual' | 'local_comercial' | 'domicilio'
    orden_origen_id     bigint,                   -- ID de la orden que generó este CxC (Flujo 2)
    estado              text   NOT NULL DEFAULT 'pendiente', -- 'pendiente' | 'parcial' | 'pagado'

    -- Auditoría
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

-- RLS
ALTER TABLE public.cxc_manuales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cxc_manuales_authenticated"
    ON public.cxc_manuales FOR ALL
    TO authenticated USING (true) WITH CHECK (true);

-- ── 3. Tabla de Abonos / Pagos parciales ─────────────────────
CREATE TABLE public.cxc_abonos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cxc_id          bigint NOT NULL REFERENCES public.cxc_manuales(id) ON DELETE CASCADE,
    monto_abono     numeric NOT NULL,
    metodo_pago     text    NOT NULL,  -- 'Efectivo' | 'Tarjeta' | 'Sinpe' | 'Otro'
    notas           text,
    registrado_por  text,              -- nombre del usuario que registró el abono
    fecha           timestamptz DEFAULT now()
);

-- RLS
ALTER TABLE public.cxc_abonos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cxc_abonos_authenticated"
    ON public.cxc_abonos FOR ALL
    TO authenticated USING (true) WITH CHECK (true);

-- ── 4. Trigger: actualizar saldo_pendiente y estado automáticamente ──
--
--  Cada vez que se inserta un abono, recalcula el saldo de la CxC
--  y actualiza su estado a 'parcial' o 'pagado' si corresponde.
-- ────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.fn_actualizar_saldo_cxc()
RETURNS TRIGGER AS $$
DECLARE
    v_total_abonos  numeric;
    v_monto_total   numeric;
    v_nuevo_saldo   numeric;
    v_nuevo_estado  text;
BEGIN
    -- Sumar todos los abonos de esta CxC
    SELECT COALESCE(SUM(monto_abono), 0)
    INTO v_total_abonos
    FROM public.cxc_abonos
    WHERE cxc_id = NEW.cxc_id;

    -- Obtener monto original
    SELECT monto_total INTO v_monto_total
    FROM public.cxc_manuales
    WHERE id = NEW.cxc_id;

    v_nuevo_saldo  := GREATEST(v_monto_total - v_total_abonos, 0);
    v_nuevo_estado := CASE
        WHEN v_nuevo_saldo <= 0        THEN 'pagado'
        WHEN v_total_abonos > 0        THEN 'parcial'
        ELSE 'pendiente'
    END;

    UPDATE public.cxc_manuales
    SET saldo_pendiente = v_nuevo_saldo,
        estado          = v_nuevo_estado,
        updated_at      = now()
    WHERE id = NEW.cxc_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_actualizar_saldo_cxc
    AFTER INSERT ON public.cxc_abonos
    FOR EACH ROW EXECUTE FUNCTION public.fn_actualizar_saldo_cxc();

-- ── 5. Forzar recarga del esquema en PostgREST ───────────────
NOTIFY pgrst, 'reload schema';
